import { describe, it, expect } from 'vitest'
import { collection, field, f } from '../src'

describe('collection', () => {
  it('creates a collection with required fields', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
        content: field({ fieldType: f.text() }),
      },
    })

    expect(posts.slug).toBe('posts')
    expect(posts.name).toBe('Posts')
    expect(posts.ownFields).toHaveProperty('title')
    expect(posts.ownFields).toHaveProperty('content')
  })

  it('auto-generates name from slug if not provided', () => {
    const blogPosts = collection({
      slug: 'blog-posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    expect(blogPosts.name).toBe('Blog Posts')
  })

  it('uses provided name over auto-generated', () => {
    const posts = collection({
      slug: 'posts',
      name: 'Blog Articles',
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    expect(posts.name).toBe('Blog Articles')
  })

  it('adds auto-generated id, createdAt, updatedAt fields', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    expect(posts.fields).toHaveProperty('id')
    expect(posts.fields).toHaveProperty('createdAt')
    expect(posts.fields).toHaveProperty('updatedAt')
  })

  it('auto-generated fields are required with defaults', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    expect(posts.fields.id.required).toBe(true)
    expect(posts.fields.createdAt.required).toBe(true)
    expect(posts.fields.updatedAt.required).toBe(true)
  })

  it('can disable individual auto-generated fields', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
      autoGeneratedFields: {
        id: false,
        createdAt: false,
        updatedAt: false,
      },
    })

    expect(posts.fields.id).toBeUndefined()
    expect(posts.fields.createdAt).toBeUndefined()
    expect(posts.fields.updatedAt).toBeUndefined()
    expect(posts.autoGeneratedFields).toEqual({
      id: false,
      createdAt: false,
      updatedAt: false,
    })
  })

  it('can disable only some auto-generated fields', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
      autoGeneratedFields: {
        createdAt: false,
      },
    })

    expect(posts.fields).toHaveProperty('id')
    expect(posts.fields.createdAt).toBeUndefined()
    expect(posts.fields).toHaveProperty('updatedAt')
  })

  it('stores admin configuration', () => {
    const posts = collection({
      slug: 'posts',
      admin: {
        description: 'Blog posts',
        icon: 'article',
      },
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    expect(posts.admin).toEqual({
      description: 'Blog posts',
      icon: 'article',
    })
  })

  it('returns null admin when not configured', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    expect(posts.admin).toBeNull()
  })

  it('returns frozen collection object', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    expect(Object.isFrozen(posts)).toBe(true)
  })

  it('has correct Symbol.toStringTag', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    expect(posts[Symbol.toStringTag]).toBe('Collection')
  })

  it('stores meta data', () => {
    const posts = collection({
      slug: 'posts',
      meta: { version: 1, author: 'test' },
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    expect(posts.meta).toEqual({ version: 1, author: 'test' })
  })

  it('returns empty meta when not provided', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    expect(posts.meta).toEqual({})
  })
})

describe('collection slug validation', () => {
  it('throws for invalid slug - uppercase', () => {
    expect(() => {
      collection({
        slug: 'Posts',
        fields: { title: field({ fieldType: f.text() }) },
      })
    }).toThrow(/Invalid slug/)
  })

  it('throws for invalid slug - spaces', () => {
    expect(() => {
      collection({
        slug: 'blog posts',
        fields: { title: field({ fieldType: f.text() }) },
      })
    }).toThrow(/Invalid slug/)
  })

  it('throws for invalid slug - starts with number', () => {
    expect(() => {
      collection({
        slug: '123posts',
        fields: { title: field({ fieldType: f.text() }) },
      })
    }).toThrow(/Invalid slug/)
  })

  it('throws for invalid slug - special characters', () => {
    expect(() => {
      collection({
        slug: 'posts!',
        fields: { title: field({ fieldType: f.text() }) },
      })
    }).toThrow(/Invalid slug/)
  })

  it('throws for empty slug', () => {
    expect(() => {
      collection({
        slug: '',
        fields: { title: field({ fieldType: f.text() }) },
      })
    }).toThrow(/slug is required/)
  })

  it('throws for reserved slug', () => {
    expect(() => {
      collection({
        slug: 'collection',
        fields: { title: field({ fieldType: f.text() }) },
      })
    }).toThrow(/reserved/)
  })

  it('allows kebab-case slugs', () => {
    const posts = collection({
      slug: 'blog-posts',
      fields: { title: field({ fieldType: f.text() }) },
    })
    expect(posts.slug).toBe('blog-posts')
  })

  it('allows snake_case slugs', () => {
    const posts = collection({
      slug: 'blog_posts',
      fields: { title: field({ fieldType: f.text() }) },
    })
    expect(posts.slug).toBe('blog_posts')
  })

  it('allows single word slugs', () => {
    const posts = collection({
      slug: 'posts',
      fields: { title: field({ fieldType: f.text() }) },
    })
    expect(posts.slug).toBe('posts')
  })
})

describe('field name validation', () => {
  it('throws when user defines a field named id', () => {
    expect(() => {
      collection({
        slug: 'posts',
        fields: { id: field({ fieldType: f.text() }) },
      })
    }).toThrow(/Field name 'id' is reserved/)
  })

  it('throws when user defines a field named createdAt', () => {
    expect(() => {
      collection({
        slug: 'posts',
        fields: { createdAt: field({ fieldType: f.text() }) },
      })
    }).toThrow(/Field name 'createdAt' is reserved/)
  })

  it('throws when user defines a field named updatedAt', () => {
    expect(() => {
      collection({
        slug: 'posts',
        fields: { updatedAt: field({ fieldType: f.text() }) },
      })
    }).toThrow(/Field name 'updatedAt' is reserved/)
  })

  it('allows disabling auto-generated field and providing custom one', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        customId: field({ fieldType: f.number() }),
      },
      autoGeneratedFields: {
        id: false,
      },
    })

    expect(posts.fields.id).toBeUndefined()
    expect(posts.fields.customId).toBeDefined()
    expect(posts.fields.customId.fieldType.type).toBe('number')
  })
})

describe('auto-generated field defaults', () => {
  it('id field has increment fieldType (maps to serial column)', () => {
    const posts = collection({
      slug: 'posts',
      fields: { title: field({ fieldType: f.text() }) },
    })

    expect(posts.fields.id.fieldType.type).toBe('increment')
  })

  it('id field has no defaultValue (auto-increment handled by database)', () => {
    const posts = collection({
      slug: 'posts',
      fields: { title: field({ fieldType: f.text() }) },
    })

    expect(posts.fields.id.defaultValue).toBeUndefined()
  })

  it('createdAt field has timestamp fieldType', () => {
    const posts = collection({
      slug: 'posts',
      fields: { title: field({ fieldType: f.text() }) },
    })

    expect(posts.fields.createdAt.fieldType.type).toBe('timestamp')
  })

  it('createdAt field has defaultFactory that returns Date', () => {
    const posts = collection({
      slug: 'posts',
      fields: { title: field({ fieldType: f.text() }) },
    })

    const date = posts.fields.createdAt.defaultValue!()
    expect(date).toBeInstanceOf(Date)
  })

  it('updatedAt field has timestamp fieldType', () => {
    const posts = collection({
      slug: 'posts',
      fields: { title: field({ fieldType: f.text() }) },
    })

    expect(posts.fields.updatedAt.fieldType.type).toBe('timestamp')
  })
})
