import { describe, it, expect } from 'vitest'
import { defineCollections } from '../src/config'
import type { Config, ConfigInput } from '../src/config/types'
import type { Collection } from '../src/collections'

describe('config', () => {
  describe('defineCollections', () => {
    it('should return config with collections record', () => {
      // Create mock collections
      const mockCollection = {
        slug: 'posts',
        name: 'Posts',
        admin: null,
        fields: {} as any,
        ownFields: {} as any,
        autoGeneratedFields: { id: true, createdAt: true, updatedAt: true },
        hooks: {},
        meta: {},
      } as Collection

      const config = defineCollections({
        db: { type: 'postgres', connection: 'postgresql://localhost:5432/mydb' },
        collections: [mockCollection],
      })

      expect(config.collections.posts).toBe(mockCollection)
    })

    it('should index collections by slug', () => {
      const posts = { slug: 'posts', name: 'Posts', fields: {}, hooks: {}, admin: null, ownFields: {}, autoGeneratedFields: {}, meta: {} } as Collection
      const users = { slug: 'users', name: 'Users', fields: {}, hooks: {}, admin: null, ownFields: {}, autoGeneratedFields: {}, meta: {} } as Collection

      const config = defineCollections({
        db: { type: 'sqlite', connection: './db.sqlite' },
        collections: [posts, users],
      })

      expect(config.collections.posts).toBe(posts)
      expect(config.collections.users).toBe(users)
    })

    it('should have db property typed correctly', () => {
      const mockCollection = {
        slug: 'posts',
        name: 'Posts',
        admin: null,
        fields: {} as any,
        ownFields: {} as any,
        autoGeneratedFields: { id: true, createdAt: true, updatedAt: true },
        hooks: {},
        meta: {},
      } as Collection

      const config = defineCollections({
        db: { type: 'postgres', connection: 'postgresql://localhost:5432/mydb' },
        collections: [mockCollection],
      })

      expect(config.db).toBeDefined()
      // db is typed as DbAccess<T> but runtime implementation is deferred
      // The type ensures config.db.posts would have correct shape when implemented
    })
  })

  describe('ConfigInput', () => {
    it('should accept db and array of collections', () => {
      const input: ConfigInput<Collection[]> = {
        db: { type: 'postgres', connection: 'postgresql://localhost:5432/mydb' },
        collections: [],
      }
      expect(input.collections).toEqual([])
      expect(input.db.type).toBe('postgres')
    })
  })
})
