/**
 * collectionToRawTable - Converts a Collection to a RawTable
 *
 * This function is part of the two-layer adapter architecture:
 *   Collection → collectionToRawTable → RawTable (Mid-Level IR) → buildDrizzleTable → Drizzle Schema
 */

import type { Field } from '../../fields'
import type { Collection } from '../../collections'
import type { RawTable, RawColumn, RawIndex } from './types'
import { fieldToRawColumn, toSnakeCase, type FieldToRawColumnOptions } from './index'
import { type Result, ok, err, type Error } from '@deessejs/core'

/**
 * Options for collectionToRawTable
 */
export interface CollectionToRawTableOptions {
  /**
   * Prefix for enum column names
   * e.g., 'post_' → 'post_status' instead of 'status'
   */
  readonly enumNamePrefix?: string
}

/**
 * Converts a Collection's slug to a table name
 *
 * @example
 * 'blog-posts' → 'blog_posts'
 * 'users' → 'users'
 */
export const collectionSlugToTableName = (slug: string): string => toSnakeCase(slug)

/**
 * Converts a Collection to a RawTable
 *
 * Rules:
 * - Table name is derived from collection slug (converted to snake_case)
 * - User fields are mapped using fieldToRawColumn
 * - Auto-generated fields (id, createdAt, updatedAt) are added based on config
 * - Indexes are created from field.unique and field.indexed properties
 * - Foreign keys are NOT resolved at this level (handled by buildRawSchema)
 *
 * @param collection - The Collection to convert
 * @param options - Optional configuration
 * @returns The corresponding RawTable
 */
export const collectionToRawTable = (
  collection: Collection<string, Record<string, Field<unknown>>>,
  options?: FieldToRawColumnOptions
): Result<RawTable, Error> => {
  const tableName = collectionSlugToTableName(collection.slug)

  // Map own fields (user-defined fields only, not auto-generated)
  const columns: Record<string, RawColumn> = {}
  const indexes: Record<string, RawIndex> = {}

  // Process user-defined fields
  for (const [fieldName, field] of Object.entries(collection.ownFields)) {
    const rawColumnResult = fieldToRawColumn(fieldName, field, options)
    if (!rawColumnResult.ok) {
      return err(rawColumnResult.error)
    }
    const rawColumn = rawColumnResult.value
    columns[rawColumn.name] = rawColumn

    // Create index from field.unique
    if (field.unique) {
      const indexName = `${rawColumn.name}_unique`
      indexes[indexName] = {
        name: indexName,
        on: rawColumn.name,
        unique: true,
      }
    }

    // Create index from field.indexed
    if (field.indexed) {
      const indexName = `${rawColumn.name}_idx`
      indexes[indexName] = {
        name: indexName,
        on: rawColumn.name,
      }
    }
  }

  // Add auto-generated fields based on configuration
  const { autoGeneratedFields } = collection

  if (autoGeneratedFields.id) {
    columns.id = {
      type: 'uuid',
      name: 'id',
      notNull: true,
      primaryKey: true,
      defaultRandom: true,
    }
  }

  if (autoGeneratedFields.createdAt) {
    columns.created_at = {
      type: 'timestamp',
      name: 'created_at',
      notNull: true,
      defaultNow: true,
    }
  }

  if (autoGeneratedFields.updatedAt) {
    columns.updated_at = {
      type: 'timestamp',
      name: 'updated_at',
      notNull: true,
      defaultNow: true,
    }
  }

  // Build the rawTable with indexes if any exist
  const rawTable: RawTable =
    Object.keys(indexes).length > 0
      ? {
          name: tableName,
          columns,
          indexes,
        }
      : {
          name: tableName,
          columns,
        }

  return ok(Object.freeze(rawTable))
}
