import { describe, it, expect } from 'vitest'
import { field, f, collection } from '../../../src'
import { buildRawSchema, type BuildRawSchemaOptions } from '../../../src/adapter/core/buildRawSchema'

describe('buildRawSchema', () => {
  it('converts a single collection to RawTable map', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    const result = buildRawSchema([posts])

    expect(result).toBeInstanceOf(Map)
    expect(result.has('posts')).toBe(true)
    expect(result.get('posts')!.name).toBe('posts')
  })

  it('converts multiple collections to RawTable map', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    const users = collection({
      slug: 'users',
      fields: {
        name: field({ fieldType: f.text() }),
      },
    })

    const result = buildRawSchema([posts, users])

    expect(result.has('posts')).toBe(true)
    expect(result.has('users')).toBe(true)
  })

  it('resolves foreign keys between collections when naming convention matches', () => {
    // FK resolution works when field name matches collection slug (after _id suffix removal)
    // 'author' field resolves to 'author' collection
    const author = collection({
      slug: 'author',
      fields: {
        name: field({ fieldType: f.text() }),
      },
    })

    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
        author: field({ fieldType: f.relation() }),
      },
    })

    const result = buildRawSchema([author, posts])

    const postsTable = result.get('posts')!
    expect(postsTable.foreignKeys).toBeDefined()
    expect(postsTable.foreignKeys!.author_fk).toBeDefined()
    expect(postsTable.foreignKeys!.author_fk.columns).toEqual(['author'])
    expect(postsTable.foreignKeys!.author_fk.foreignColumns).toEqual([
      { name: 'id', table: 'author' },
    ])
  })

  it('handles _id suffix in column names for FK resolution', () => {
    // 'category_id' field resolves to 'category' collection
    const category = collection({
      slug: 'category',
      fields: {
        name: field({ fieldType: f.text() }),
      },
    })

    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
        categoryId: field({ fieldType: f.relation() }),
      },
    })

    const result = buildRawSchema([category, posts])

    const postsTable = result.get('posts')!
    expect(postsTable.foreignKeys).toBeDefined()
    expect(postsTable.foreignKeys!.category_id_fk).toBeDefined()
    expect(postsTable.foreignKeys!.category_id_fk.columns).toEqual(['category_id'])
    expect(postsTable.foreignKeys!.category_id_fk.foreignColumns).toEqual([
      { name: 'id', table: 'category' },
    ])
  })

  it('does not create FK for uuid columns that are primary keys', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
      autoGeneratedFields: { id: true, createdAt: false, updatedAt: false },
    })

    const result = buildRawSchema([posts])

    const postsTable = result.get('posts')!
    // id column should be primary key, not a foreign key
    expect(postsTable.columns.id.primaryKey).toBe(true)
    expect(postsTable.foreignKeys).toBeUndefined()
  })

  it('does not create FK for non-uuid columns', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text(), indexed: true }),
        viewCount: field({ fieldType: f.number() }),
      },
    })

    const result = buildRawSchema([posts])

    const postsTable = result.get('posts')!
    expect(postsTable.foreignKeys).toBeUndefined()
  })

  it('does not create FK when target collection does not exist', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
        author: field({ fieldType: f.relation() }),
      },
    })

    const result = buildRawSchema([posts])

    const postsTable = result.get('posts')!
    expect(postsTable.foreignKeys).toBeUndefined()
  })

  it('applies enumNamePrefix to all collections', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        status: field({ fieldType: f.select(['draft', 'published']) }),
      },
    })

    const options: BuildRawSchemaOptions = { enumNamePrefix: 'post_' }
    const result = buildRawSchema([posts], options)

    expect(result.get('posts')!.columns.status.enumName).toBe('post_status')
  })

  it('uses custom resolveRelation function', () => {
    const authors = collection({
      slug: 'authors',
      fields: {
        name: field({ fieldType: f.text() }),
      },
    })

    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
        writer: field({ fieldType: f.relation() }),
      },
    })

    // Custom resolver that maps 'writer' -> 'authors'
    const options: BuildRawSchemaOptions = {
      resolveRelation: (fieldName) => {
        if (fieldName === 'writer') return 'authors'
        return fieldName.replace(/Id$/, '').replace(/_id$/, '')
      },
    }

    const result = buildRawSchema([authors, posts], options)

    const postsTable = result.get('posts')!
    expect(postsTable.foreignKeys).toBeDefined()
    expect(postsTable.foreignKeys!.writer_fk).toBeDefined()
    expect(postsTable.foreignKeys!.writer_fk.foreignColumns).toEqual([
      { name: 'id', table: 'authors' },
    ])
  })

  it('returns empty Map for empty array', () => {
    const result = buildRawSchema([])
    expect(result.size).toBe(0)
  })

  it('handles kebab-case collection slugs (no conversion)', () => {
    // Slugs must be lowercase kebab-case
    // toSnakeCase doesn't convert kebab-case, so table name stays as-is
    const blogPosts = collection({
      slug: 'blog-posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    const result = buildRawSchema([blogPosts])

    // Table name is not converted from kebab-case
    expect(result.has('blog-posts')).toBe(true)
    expect(result.get('blog-posts')!.name).toBe('blog-posts')
  })

  it('handles collection with no user-defined fields', () => {
    const posts = collection({
      slug: 'posts',
      fields: {},
    })

    const result = buildRawSchema([posts])

    const postsTable = result.get('posts')!
    // Should still have auto-generated fields
    expect(postsTable.columns.id).toBeDefined()
    expect(postsTable.columns.created_at).toBeDefined()
    expect(postsTable.columns.updated_at).toBeDefined()
    // No user fields
    expect(Object.keys(postsTable.columns).filter(k => !['id', 'created_at', 'updated_at'].includes(k))).toHaveLength(0)
  })

  it('creates indexes from unique and indexed fields', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        slug: field({ fieldType: f.text(), unique: true }),
        category: field({ fieldType: f.text(), indexed: true }),
        author: field({ fieldType: f.relation(), unique: true }),
      },
    })

    const result = buildRawSchema([posts])

    const postsTable = result.get('posts')!
    expect(postsTable.indexes).toBeDefined()
    expect(postsTable.indexes!.slug_unique).toBeDefined()
    expect(postsTable.indexes!.category_idx).toBeDefined()
    expect(postsTable.indexes!.author_unique).toBeDefined()
  })
})
