import { describe, it, expect } from 'vitest'
import { isOk } from '@deessejs/core'
import { field, f, collection } from '../../../src'
import { collectionToRawTable, collectionSlugToTableName, type CollectionToRawTableOptions } from '../../../src/adapter/core/collectionToRawTable'

describe('collectionSlugToTableName', () => {
  // Note: Collection slugs must be lowercase (kebab-case or snake_case)
  // so in practice, most slugs won't be converted

  it('keeps lowercase slug unchanged', () => {
    expect(collectionSlugToTableName('users')).toBe('users')
  })

  it('keeps kebab-case slug unchanged (toSnakeCase does not handle kebab-case)', () => {
    expect(collectionSlugToTableName('blog-posts')).toBe('blog-posts')
  })

  it('keeps snake_case slug unchanged', () => {
    expect(collectionSlugToTableName('blog_posts')).toBe('blog_posts')
  })
})

describe('collectionToRawTable', () => {
  it('converts a simple collection to RawTable', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
        content: field({ fieldType: f.text() }),
      },
    })

    const result = collectionToRawTable(posts)

    expect(result.ok).toBe(true)
    expect(result.value.table.name).toBe('posts')
    expect(result.value.table.columns).toHaveProperty('title')
    expect(result.value.table.columns).toHaveProperty('content')
    expect(result.value.table.columns.id).toBeDefined()
    expect(result.value.table.columns.created_at).toBeDefined()
    expect(result.value.table.columns.updated_at).toBeDefined()
  })

  it('maps field types correctly', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
        isPublished: field({ fieldType: f.boolean() }),
        viewCount: field({ fieldType: f.number() }),
        price: field({ fieldType: f.decimal(10, 2) }),
        status: field({ fieldType: f.select(['draft', 'published']) }),
      },
    })

    const result = collectionToRawTable(posts)

    expect(result.ok).toBe(true)
    expect(result.value.table.columns.title.type).toBe('varchar')
    expect(result.value.table.columns.is_published.type).toBe('boolean')
    expect(result.value.table.columns.view_count.type).toBe('integer')
    expect(result.value.table.columns.price.type).toBe('decimal')
    expect(result.value.table.columns.price.precision).toBe(10)
    expect(result.value.table.columns.price.scale).toBe(2)
    expect(result.value.table.columns.status.type).toBe('enum')
  })

  it('creates unique indexes for unique fields', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        slug: field({ fieldType: f.text(), unique: true }),
        email: field({ fieldType: f.email(), unique: true }),
      },
    })

    const result = collectionToRawTable(posts)

    expect(result.ok).toBe(true)
    expect(result.value.table.indexes).toBeDefined()
    expect(result.value.table.indexes!.slug_unique).toBeDefined()
    expect(result.value.table.indexes!.slug_unique.unique).toBe(true)
    expect(result.value.table.indexes!.slug_unique.on).toBe('slug')
    expect(result.value.table.indexes!.email_unique).toBeDefined()
  })

  it('creates indexes for indexed fields', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        category: field({ fieldType: f.text(), indexed: true }),
        author: field({ fieldType: f.relation() }),
      },
    })

    const result = collectionToRawTable(posts)

    expect(result.ok).toBe(true)
    expect(result.value.table.indexes).toBeDefined()
    expect(result.value.table.indexes!.category_idx).toBeDefined()
    expect(result.value.table.indexes!.category_idx.unique).toBeUndefined()
    expect(result.value.table.indexes!.category_idx.on).toBe('category')
  })

  it('respects autoGeneratedFields config', () => {
    const posts = collection({
      slug: 'posts',
      autoGeneratedFields: { id: true, createdAt: false, updatedAt: false },
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    const result = collectionToRawTable(posts)

    expect(result.ok).toBe(true)
    expect(result.value.table.columns.id).toBeDefined()
    expect(result.value.table.columns.created_at).toBeUndefined()
    expect(result.value.table.columns.updated_at).toBeUndefined()
  })

  it('does not create notNull for fields with default values', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text(), required: true }),
        content: field({ fieldType: f.text(), defaultValue: 'default content' }),
      },
    })

    const result = collectionToRawTable(posts)

    expect(result.ok).toBe(true)
    expect(result.value.table.columns.title.notNull).toBe(true)
    expect(result.value.table.columns.content.notNull).toBeUndefined()
    expect(result.value.table.columns.content.default).toBe('default content')
  })

  it('handles relation fields as uuid type', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        author: field({ fieldType: f.relation() }),
      },
    })

    const result = collectionToRawTable(posts)

    expect(result.ok).toBe(true)
    expect(result.value.table.columns.author.type).toBe('uuid')
    expect(result.value.table.columns.author.notNull).toBeUndefined() // relation fields are optional by default
  })

  it('does not set notNull for optional relation fields', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        author: field({ fieldType: f.relation() }),
      },
    })

    const result = collectionToRawTable(posts)

    expect(result.ok).toBe(true)
    expect(result.value.table.columns.author.notNull).toBeUndefined()
  })

  it('sets notNull for required relation fields', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        author: field({ fieldType: f.relation(), required: true }),
      },
    })

    const result = collectionToRawTable(posts)

    expect(result.ok).toBe(true)
    expect(result.value.table.columns.author.notNull).toBe(true)
  })

  it('applies enumNamePrefix when provided', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        status: field({ fieldType: f.select(['draft', 'published']) }),
      },
    })

    const options: CollectionToRawTableOptions = { enumNamePrefix: 'post_' }
    const result = collectionToRawTable(posts, options)

    expect(result.ok).toBe(true)
    expect(result.value.table.columns.status.enumName).toBe('post_status')
  })

  it('returns frozen RawTable', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
      },
    })

    const result = collectionToRawTable(posts)

    expect(result.ok).toBe(true)
    expect(() => {
      ;(result.value.table as any).name = 'changed'
    }).toThrow()
  })

  it('handles all field types correctly', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        email: field({ fieldType: f.email() }),
        website: field({ fieldType: f.url() }),
        avatar: field({ fieldType: f.file() }),
        bio: field({ fieldType: f.richtext() }),
        birthDate: field({ fieldType: f.date() }),
        publishedAt: field({ fieldType: f.timestamp() }),
        deletedAt: field({ fieldType: f.timestampTz() }),
        metadata: field({ fieldType: f.json() }),
        config: field({ fieldType: f.jsonb() }),
        tags: field({ fieldType: f.array(f.text()) }),
        externalId: field({ fieldType: f.uuid() }),
      },
    })

    const result = collectionToRawTable(posts)

    expect(result.ok).toBe(true)
    expect(result.value.table.columns.email.type).toBe('varchar')
    expect(result.value.table.columns.website.type).toBe('varchar')
    expect(result.value.table.columns.avatar.type).toBe('varchar')
    expect(result.value.table.columns.bio.type).toBe('text')
    expect(result.value.table.columns.birth_date.type).toBe('date')
    expect(result.value.table.columns.published_at.type).toBe('timestamp')
    expect(result.value.table.columns.deleted_at.type).toBe('timestamptz')
    expect(result.value.table.columns.metadata.type).toBe('json')
    expect(result.value.table.columns.config.type).toBe('jsonb')
    expect(result.value.table.columns.tags.type).toBe('json')
    expect(result.value.table.columns.external_id.type).toBe('uuid')
  })

  it('creates junction table for hasMany relations', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        title: field({ fieldType: f.text() }),
        tags: field({
          fieldType: f.relation({ collection: 'tags', hasMany: true }),
        }),
      },
    })

    const result = collectionToRawTable(posts)

    expect(result.ok).toBe(true)
    // Main table should not have a tags column (junction table is created instead)
    expect(result.value.table.columns.tags).toBeUndefined()
    // Junction tables should be created
    expect(result.value.junctionTables).toHaveLength(1)
    expect(result.value.junctionTables[0].name).toBe('posts_tags')
    expect(result.value.junctionTables[0].parentTable).toBe('posts')
    expect(result.value.junctionTables[0].targetTable).toBe('tags')
  })

  it('does not create junction table for regular relation fields', () => {
    const posts = collection({
      slug: 'posts',
      fields: {
        author: field({ fieldType: f.relation() }),
      },
    })

    const result = collectionToRawTable(posts)

    expect(result.ok).toBe(true)
    expect(result.value.table.columns.author).toBeDefined()
    expect(result.value.junctionTables).toHaveLength(0)
  })
})
