import { describe, it, expect } from 'vitest'
import { createPostgresSchema } from '../../../src/adapter/postgresql'
import { collection, field, f } from '../../../src'

describe('createPostgresSchema', () => {
  describe('returns correct shape', () => {
    it('should return an object with table names as keys', () => {
      const posts = collection({
        slug: 'posts',
        fields: {
          title: field({ fieldType: f.text() }),
        },
      })

      const schema = createPostgresSchema([posts])

      expect(schema).toBeDefined()
      expect(typeof schema).toBe('object')
      expect('posts' in schema).toBe(true)
    })

    it('should return tables as values', () => {
      const posts = collection({
        slug: 'posts',
        fields: {
          title: field({ fieldType: f.text() }),
        },
      })

      const schema = createPostgresSchema([posts])

      expect(schema.posts).toBeDefined()
      expect(typeof schema.posts).toBe('object')
    })
  })

  describe('auto-generated fields', () => {
    it('should include id field', () => {
      const posts = collection({
        slug: 'posts',
        fields: {
          title: field({ fieldType: f.text() }),
        },
      })

      const schema = createPostgresSchema([posts])
      const postsTable = schema.posts as Record<string, unknown>

      expect(postsTable.id).toBeDefined()
    })

    it('should include created_at field', () => {
      const posts = collection({
        slug: 'posts',
        fields: {
          title: field({ fieldType: f.text() }),
        },
      })

      const schema = createPostgresSchema([posts])
      const postsTable = schema.posts as Record<string, unknown>

      expect(postsTable.created_at).toBeDefined()
    })

    it('should include updated_at field', () => {
      const posts = collection({
        slug: 'posts',
        fields: {
          title: field({ fieldType: f.text() }),
        },
      })

      const schema = createPostgresSchema([posts])
      const postsTable = schema.posts as Record<string, unknown>

      expect(postsTable.updated_at).toBeDefined()
    })

    it('should respect autoGeneratedFields config', () => {
      const posts = collection({
        slug: 'posts',
        fields: {
          title: field({ fieldType: f.text() }),
        },
        autoGeneratedFields: {
          id: true,
          createdAt: false,
          updatedAt: true,
        },
      })

      const schema = createPostgresSchema([posts])
      const postsTable = schema.posts as Record<string, unknown>

      expect(postsTable.id).toBeDefined()
      expect(postsTable.created_at).toBeUndefined()
      expect(postsTable.updated_at).toBeDefined()
    })
  })

  describe('user-defined fields', () => {
    it('should include text fields', () => {
      const posts = collection({
        slug: 'posts',
        fields: {
          title: field({ fieldType: f.text() }),
        },
      })

      const schema = createPostgresSchema([posts])
      const postsTable = schema.posts as Record<string, unknown>

      expect(postsTable.title).toBeDefined()
    })

    it('should include number fields', () => {
      const posts = collection({
        slug: 'posts',
        fields: {
          view_count: field({ fieldType: f.number() }),
        },
      })

      const schema = createPostgresSchema([posts])
      const postsTable = schema.posts as Record<string, unknown>

      expect(postsTable.view_count).toBeDefined()
    })

    it('should include boolean fields', () => {
      const posts = collection({
        slug: 'posts',
        fields: {
          published: field({ fieldType: f.boolean() }),
        },
      })

      const schema = createPostgresSchema([posts])
      const postsTable = schema.posts as Record<string, unknown>

      expect(postsTable.published).toBeDefined()
    })

    it('should include timestamp fields', () => {
      const posts = collection({
        slug: 'posts',
        fields: {
          published_at: field({ fieldType: f.timestamp() }),
        },
      })

      const schema = createPostgresSchema([posts])
      const postsTable = schema.posts as Record<string, unknown>

      expect(postsTable.published_at).toBeDefined()
    })

    it('should include uuid fields', () => {
      const posts = collection({
        slug: 'posts',
        fields: {
          author_id: field({ fieldType: f.uuid() }),
        },
      })

      const schema = createPostgresSchema([posts])
      const postsTable = schema.posts as Record<string, unknown>

      expect(postsTable.author_id).toBeDefined()
    })

    it('should include email fields', () => {
      const users = collection({
        slug: 'users',
        fields: {
          email: field({ fieldType: f.email() }),
        },
      })

      const schema = createPostgresSchema([users])
      const usersTable = schema.users as Record<string, unknown>

      expect(usersTable.email).toBeDefined()
    })
  })

  describe('indexes', () => {
    it('should support unique indexes via field options', () => {
      const users = collection({
        slug: 'users',
        fields: {
          email: field({ fieldType: f.email(), unique: true }),
        },
      })

      const schema = createPostgresSchema([users])
      expect(schema.users).toBeDefined()
    })

    it('should support indexed fields', () => {
      const posts = collection({
        slug: 'posts',
        fields: {
          title: field({ fieldType: f.text(), indexed: true }),
        },
      })

      const schema = createPostgresSchema([posts])
      expect(schema.posts).toBeDefined()
    })
  })

  describe('multiple collections', () => {
    it('should create schema for multiple collections', () => {
      const posts = collection({
        slug: 'posts',
        fields: {
          title: field({ fieldType: f.text() }),
        },
      })

      const users = collection({
        slug: 'users',
        fields: {
          name: field({ fieldType: f.text() }),
          email: field({ fieldType: f.email() }),
        },
      })

      const schema = createPostgresSchema([posts, users])

      expect(schema.posts).toBeDefined()
      expect(schema.users).toBeDefined()
      expect(Object.keys(schema).sort()).toEqual(['posts', 'users'])
    })

    it('should handle collection relationships', () => {
      const users = collection({
        slug: 'users',
        fields: {
          name: field({ fieldType: f.text() }),
        },
      })

      const posts = collection({
        slug: 'posts',
        fields: {
          title: field({ fieldType: f.text() }),
          author_id: field({ fieldType: f.uuid() }),
        },
      })

      const schema = createPostgresSchema([users, posts])

      expect(schema.users).toBeDefined()
      expect(schema.posts).toBeDefined()
    })
  })
})