/**
 * @deessejs/collections Snippet 01: Basic Collection Definition
 *
 * This example demonstrates how to define a basic collection with fields
 * using the @deessejs/collections DSL.
 *
 * Run with: npx tsx examples/snippets/01-basic-collection.ts
 */

import { collection, field, f, defineCollections, sqlite } from '@deessejs/collections'

// =============================================================================
// Defining a Basic Collection
// =============================================================================

/**
 * Collections are the core building blocks in @deessejs/collections.
 * They define the schema for a group of related records (similar to a table
 * in SQL or a model in an ORM).
 *
 * Each collection has:
 * - slug: Unique identifier (kebab-case recommended)
 * - name: Human-readable name (auto-generated from slug if not provided)
 * - fields: Record of field definitions
 * - admin: Optional admin UI configuration
 * - hooks: Optional lifecycle hooks
 * - autoGeneratedFields: Configuration for id, createdAt, updatedAt fields
 */
const posts = collection({
  slug: 'posts',
  name: 'Blog Posts',
  admin: {
    description: 'Blog posts for the website',
    icon: 'article',
  },
  fields: {
    // Text field for the post title
    title: field({
      fieldType: f.text(),
      required: true,
    }),
    // Text field for the post content (body)
    content: field({
      fieldType: f.text(),
    }),
    // Boolean flag to publish the post
    published: field({
      fieldType: f.boolean(),
      defaultValue: false,
    }),
  },
})

// =============================================================================
// Auto-Generated Fields
// =============================================================================

/**
 * By default, collections automatically include three fields:
 * - id: UUID string (auto-generated using crypto.randomUUID())
 * - createdAt: Date timestamp (auto-set on creation)
 * - updatedAt: Date timestamp (auto-updated on modification)
 *
 * You can disable any of these in the autoGeneratedFields config.
 */
const users = collection({
  slug: 'users',
  // Disable auto-generated id - we'll use our own
  autoGeneratedFields: {
    id: false, // Disable auto-generated id
    createdAt: true,
    updatedAt: true,
  },
  fields: {
    // Using f.uuid() for custom user IDs
    userId: field({
      fieldType: f.uuid(),
      required: true,
    }),
    username: field({
      fieldType: f.text(),
      required: true,
      unique: true,
    }),
  },
})

// =============================================================================
// Building a Config with Multiple Collections
// =============================================================================

/**
 * Use defineCollections to combine multiple collections into a schema.
 * This is typically used with a database driver to perform operations.
 */
const config = defineCollections({
  db: sqlite({ path: ':memory:' }),
  collections: [posts, users],
})

// =============================================================================
// Type Inference
// =============================================================================

/**
 * @deessejs/collections provides type inference for your collections.
 * GetCollectionType<T> extracts the TypeScript type from a collection.
 *
 * Note: This is a schema definition example. To actually perform
 * CRUD operations, you would need a database driver integration.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
type PostType = {
  id: string
  title: string
  content?: string
  published: boolean
  createdAt: Date
  updatedAt: Date
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
type UserType = {
  userId: string
  username: string
  createdAt: Date
  updatedAt: Date
}

// =============================================================================
// Usage Example
// =============================================================================

console.log('=== @deessejs/collections - Basic Collection ===')
console.log(`Posts collection slug: ${posts.slug}`)
console.log(`Posts collection name: ${posts.name}`)
console.log(`Posts fields:`, Object.keys(posts.fields))
console.log(`Posts hooks:`, Object.keys(posts.hooks))
console.log('')
console.log(`Users collection slug: ${users.slug}`)
console.log(`Users fields:`, Object.keys(users.fields))
console.log('')
console.log('Collection definition complete!')
