// collection() function - DSL for defining collections

import { err, ok, unit, type Result, type Unit, error } from '@deessejs/core'
import { z } from 'zod'
import { field, f } from '../fields'
import type { Field } from '../fields'
import type {
  Collection,
  CollectionConfig,
  CollectionFields,
  CollectionHooks,
  AutoGeneratedFieldsConfig,
} from './types'

/**
 * Slug validation regex - lowercase, numbers, hyphens
 */
const SLUG_REGEX = /^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$/

/**
 * Reserved slugs that cannot be used
 */
const RESERVED_SLUGS = new Set([
  'collection',
  'config',
  'db',
  'field',
  'fields',
  'index',
  'type',
  'types',
])

/**
 * Reserved field names that conflict with auto-generated fields
 */
const RESERVED_FIELD_NAMES = new Set(['id', 'createdAt', 'updatedAt'])

/**
 * Error builder for slug validation errors
 */
const SlugValidationError = error({
  name: 'SlugValidation',
  schema: z.object({
    slug: z.unknown(),
    reason: z.enum(['required', 'format', 'reserved']),
  }),
  message: (args) => {
    if (args.reason === 'required') return 'Collection slug is required and must be a string'
    if (args.reason === 'format') return `Invalid slug '${String(args.slug)}'. Slug must be lowercase, start with a letter, and contain only letters, numbers, and hyphens/underscores.`
    return `Slug '${String(args.slug)}' is reserved. Please choose a different name.`
  },
})

/**
 * Error builder for reserved field name errors
 */
const ReservedFieldError = error({
  name: 'ReservedField',
  schema: z.object({
    fieldName: z.string(),
  }),
  message: (args) => `Field name '${args.fieldName}' is reserved. It conflicts with auto-generated field '${args.fieldName}'. Either remove it or disable the auto-generated field via autoGeneratedFields.`,
})

/**
 * Validate a collection slug
 */
const validateSlug = (slug: unknown): Result<Unit, ReturnType<typeof SlugValidationError>> => {
  if (!slug || typeof slug !== 'string') {
    return err(SlugValidationError({ slug, reason: 'required' }))
  }

  if (!SLUG_REGEX.test(slug)) {
    return err(SlugValidationError({ slug, reason: 'format' }))
  }

  if (RESERVED_SLUGS.has(slug)) {
    return err(SlugValidationError({ slug, reason: 'reserved' }))
  }

  return ok(unit)
}

/**
 * Validate that user fields don't conflict with auto-generated field names
 */
const validateFieldNames = <TFields extends Record<string, Field<unknown>>>(
  fields: TFields
): Result<Unit, ReturnType<typeof ReservedFieldError>> => {
  for (const fieldName of Object.keys(fields)) {
    if (RESERVED_FIELD_NAMES.has(fieldName)) {
      return err(ReservedFieldError({ fieldName }))
    }
  }

  return ok(unit)
}

/**
 * Convert a slug to a human-readable name
 * 'blog-posts' -> 'Blog Posts'
 * 'users' -> 'Users'
 */
const slugToName = (slug: string): string =>
  slug
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')

/**
 * Build auto-generated fields based on configuration
 */
const buildAutoGeneratedFields = (
  config: Required<AutoGeneratedFieldsConfig>
): { id: Field<string>; createdAt: Field<Date>; updatedAt: Field<Date> } => {
  const autoFields: { id?: Field<string>; createdAt?: Field<Date>; updatedAt?: Field<Date> } = {}

  if (config.id) {
    autoFields.id = field({
      fieldType: f.uuid(),
      required: true,
      defaultFactory: () => crypto.randomUUID(),
    })
  }

  if (config.createdAt) {
    autoFields.createdAt = field({
      fieldType: f.timestamp(),
      required: true,
      defaultFactory: () => new Date(),
    })
  }

  if (config.updatedAt) {
    autoFields.updatedAt = field({
      fieldType: f.timestamp(),
      required: true,
      defaultFactory: () => new Date(),
    })
  }

  return autoFields as { id: Field<string>; createdAt: Field<Date>; updatedAt: Field<Date> }
}

/**
 * collection - Define a collection schema
 *
 * @param config - Collection configuration
 * @returns A Collection definition
 *
 * @example
 * ```typescript
 * const posts = collection({
 *   slug: 'posts',
 *   name: 'Blog Posts',
 *   fields: {
 *     title: field({ fieldType: f.text() }),
 *     content: field({ fieldType: f.text() }),
 *     published: field({ fieldType: f.boolean() }),
 *   }
 * })
 * ```
 */
export const collection = <
  TSlug extends string,
  TFields extends Record<string, Field<unknown>>,
>(
  config: CollectionConfig<TSlug, TFields>
): Collection<TSlug, TFields> => {
  // Validate slug
  const slugResult = validateSlug(config.slug)
  if (!slugResult.ok) {
    throw slugResult.error
  }

  // Validate field names don't conflict with auto-generated fields
  const fieldNamesResult = validateFieldNames(config.fields)
  if (!fieldNamesResult.ok) {
    throw fieldNamesResult.error
  }

  // Default auto-generated fields configuration
  const autoGeneratedFieldsConfig: Required<AutoGeneratedFieldsConfig> = {
    id: true,
    createdAt: true,
    updatedAt: true,
    ...config.autoGeneratedFields,
  }

  // Build auto-generated fields
  const autoFields = buildAutoGeneratedFields(autoGeneratedFieldsConfig)

  // Combine user fields with auto-generated fields
  const allFields: CollectionFields<TFields> = {
    ...config.fields,
    ...autoFields,
  } as CollectionFields<TFields>

  // Default empty hooks
  const hooks: CollectionHooks<TSlug, TFields> = config.hooks ?? {}

  // Build the collection object
  const collection: Collection<TSlug, TFields> = Object.freeze({
    slug: config.slug,
    name: config.name ?? slugToName(config.slug),
    admin: config.admin
      ? {
          description: config.admin.description,
          icon: config.admin.icon,
        }
      : null,
    fields: allFields,
    ownFields: config.fields,
    autoGeneratedFields: autoGeneratedFieldsConfig,
    meta: config.meta ?? {},
    hooks,
    [Symbol.toStringTag]: 'Collection' as const,
  })

  return collection
}
