// collection() function - DSL for defining collections

import { field, f } from '../fields'
import type { Field } from '../fields'
import type {
  Collection,
  CollectionConfig,
  CollectionFields,
  AutoGeneratedFieldsConfig,
} from './types'

/**
 * Slug validation regex - lowercase, numbers, hyphens
 */
const SLUG_REGEX = /^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$/

/**
 * Reserved slugs that cannot be used
 */
const RESERVED_SLUGS = new Set([
  'collection',
  'config',
  'db',
  'field',
  'fields',
  'index',
  'type',
  'types',
])

/**
 * Reserved field names that conflict with auto-generated fields
 */
const RESERVED_FIELD_NAMES = new Set(['id', 'createdAt', 'updatedAt'])

/**
 * Validate a collection slug
 */
function validateSlug(slug: string): void {
  if (!slug || typeof slug !== 'string') {
    throw new Error('Collection slug is required and must be a string')
  }

  if (!SLUG_REGEX.test(slug)) {
    throw new Error(
      `Invalid slug '${slug}'. Slug must be lowercase, start with a letter, and contain only letters, numbers, and hyphens/underscores. Example: 'blog-posts'`
    )
  }

  if (RESERVED_SLUGS.has(slug)) {
    throw new Error(`Slug '${slug}' is reserved. Please choose a different name.`)
  }
}

/**
 * Validate that user fields don't conflict with auto-generated field names
 */
function validateFieldNames<TFields extends Record<string, Field<unknown>>>(
  fields: TFields
): void {
  for (const fieldName of Object.keys(fields)) {
    if (RESERVED_FIELD_NAMES.has(fieldName)) {
      throw new Error(
        `Field name '${fieldName}' is reserved. It conflicts with auto-generated field '${fieldName}'. Either remove it or disable the auto-generated field via autoGeneratedFields: { ${fieldName}: false }.`
      )
    }
  }
}

/**
 * Convert a slug to a human-readable name
 * 'blog-posts' -> 'Blog Posts'
 * 'users' -> 'Users'
 */
function slugToName(slug: string): string {
  return slug
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

/**
 * Build auto-generated fields based on configuration
 */
function buildAutoGeneratedFields(
  config: Required<AutoGeneratedFieldsConfig>
): { id: Field<string>; createdAt: Field<Date>; updatedAt: Field<Date> } {
  const autoFields: { id?: Field<string>; createdAt?: Field<Date>; updatedAt?: Field<Date> } = {}

  if (config.id) {
    autoFields.id = field({
      fieldType: f.uuid(),
      required: true,
      defaultFactory: () => crypto.randomUUID(),
    })
  }

  if (config.createdAt) {
    autoFields.createdAt = field({
      fieldType: f.timestamp(),
      required: true,
      defaultFactory: () => new Date(),
    })
  }

  if (config.updatedAt) {
    autoFields.updatedAt = field({
      fieldType: f.timestamp(),
      required: true,
      defaultFactory: () => new Date(),
    })
  }

  return autoFields as { id: Field<string>; createdAt: Field<Date>; updatedAt: Field<Date> }
}

/**
 * collection - Define a collection schema
 *
 * @param config - Collection configuration
 * @returns A Collection definition
 *
 * @example
 * ```typescript
 * const posts = collection({
 *   slug: 'posts',
 *   name: 'Blog Posts',
 *   fields: {
 *     title: field({ fieldType: f.text() }),
 *     content: field({ fieldType: f.text() }),
 *     published: field({ fieldType: f.boolean() }),
 *   }
 * })
 * ```
 */
export function collection<TFields extends Record<string, Field<unknown>>>(
  config: CollectionConfig<TFields>
): Collection<TFields> {
  // Validate slug
  validateSlug(config.slug)

  // Validate field names don't conflict with auto-generated fields
  validateFieldNames(config.fields)

  // Default auto-generated fields configuration
  const autoGeneratedFieldsConfig: Required<AutoGeneratedFieldsConfig> = {
    id: true,
    createdAt: true,
    updatedAt: true,
    ...config.autoGeneratedFields,
  }

  // Build auto-generated fields
  const autoFields = buildAutoGeneratedFields(autoGeneratedFieldsConfig)

  // Combine user fields with auto-generated fields
  const allFields: CollectionFields<TFields> = {
    ...config.fields,
    ...autoFields,
  } as CollectionFields<TFields>

  // Build the collection object
  const collection: Collection<TFields> = Object.freeze({
    slug: config.slug,
    name: config.name ?? slugToName(config.slug),
    admin: config.admin
      ? {
          description: config.admin.description,
          icon: config.admin.icon,
        }
      : null,
    fields: allFields,
    ownFields: config.fields,
    autoGeneratedFields: autoGeneratedFieldsConfig,
    meta: config.meta ?? {},
    [Symbol.toStringTag]: 'Collection' as const,
  })

  return collection
}
