// collection() function - DSL for defining collections

import { field, f } from '../fields'
import type { Field } from '../fields'
import type {
  Collection,
  CollectionConfig,
  CollectionFields,
  CollectionCreationContext,
  AutoGeneratedFieldsConfig,
} from './types'

/**
 * Slug validation regex - lowercase, numbers, hyphens
 */
const SLUG_REGEX = /^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$/

/**
 * Reserved slugs that cannot be used
 */
const RESERVED_SLUGS = new Set([
  'collection',
  'config',
  'db',
  'field',
  'fields',
  'index',
  'type',
  'types',
])

/**
 * Validate a collection slug
 */
function validateSlug(slug: string): void {
  if (!slug || typeof slug !== 'string') {
    throw new Error('Collection slug is required and must be a string')
  }

  if (!SLUG_REGEX.test(slug)) {
    throw new Error(
      `Invalid slug '${slug}'. Slug must be lowercase, start with a letter, and contain only letters, numbers, and hyphens/underscores. Example: 'blog-posts'`
    )
  }

  if (RESERVED_SLUGS.has(slug)) {
    throw new Error(`Slug '${slug}' is reserved. Please choose a different name.`)
  }
}

/**
 * Convert a slug to a human-readable name
 * 'blog-posts' -> 'Blog Posts'
 * 'users' -> 'Users'
 */
function slugToName(slug: string): string {
  return slug
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

/**
 * Build auto-generated fields based on configuration
 */
function buildAutoGeneratedFields(
  config: Required<AutoGeneratedFieldsConfig>,
  _context: CollectionCreationContext
): { id: Field<string>; createdAt: Field<Date>; updatedAt: Field<Date> } {
  const fields: { id?: Field<string>; createdAt?: Field<Date>; updatedAt?: Field<Date> } = {}

  if (config.id) {
    fields.id = field({
      fieldType: f.uuid(),
      required: true,
      defaultFactory: () => crypto.randomUUID(),
    })
  }

  if (config.createdAt) {
    fields.createdAt = field({
      fieldType: f.timestamp(),
      required: true,
      defaultFactory: () => new Date(),
    })
  }

  if (config.updatedAt) {
    fields.updatedAt = field({
      fieldType: f.timestamp(),
      required: true,
      defaultFactory: () => new Date(),
    })
  }

  return fields as { id: Field<string>; createdAt: Field<Date>; updatedAt: Field<Date> }
}

/**
 * collection - Define a collection schema
 *
 * @param config - Collection configuration
 * @returns A Collection definition
 *
 * @example
 * ```typescript
 * const posts = collection({
 *   slug: 'posts',
 *   name: 'Blog Posts',
 *   fields: {
 *     title: field({ fieldType: f.text() }),
 *     content: field({ fieldType: f.text() }),
 *     published: field({ fieldType: f.boolean() }),
 *   }
 * })
 * ```
 */
export function collection<TFields extends Record<string, Field<unknown>>>(
  config: CollectionConfig<TFields>
): Collection<TFields> {
  // Validate slug
  validateSlug(config.slug)

  // Default auto-generated fields configuration
  const autoGeneratedFieldsConfig: Required<AutoGeneratedFieldsConfig> = {
    id: true,
    createdAt: true,
    updatedAt: true,
    ...config.autoGeneratedFields,
  }

  const context: CollectionCreationContext = {
    slug: config.slug,
    autoGeneratedFields: autoGeneratedFieldsConfig,
  }

  // Build auto-generated fields
  const autoFields = buildAutoGeneratedFields(autoGeneratedFieldsConfig, context)

  // Combine user fields with auto-generated fields
  const allFields: CollectionFields<TFields> = {
    ...config.fields,
    ...autoFields,
  } as CollectionFields<TFields>

  // Build the collection object
  const collection: Collection<TFields> = Object.freeze({
    slug: config.slug,
    name: config.name ?? slugToName(config.slug),
    admin: config.admin
      ? {
          description: config.admin.description,
          icon: config.admin.icon,
        }
      : null,
    fields: allFields,
    ownFields: config.fields,
    autoGeneratedFields: autoGeneratedFieldsConfig,
    meta: config.meta ?? {},
    [Symbol.toStringTag]: 'Collection' as const,
  })

  return collection
}
