// Collection types - DSL for defining collections

import type { Field } from '../fields'
import type {
  HookOperation,
  BaseHookContext,
  CreateHookContext,
  ReadHookContext,
  UpdateHookContext,
  DeleteHookContext,
  HookHandler,
  CollectionHooks,
  InferFieldType,
  InferFieldTypes,
} from './hooks'

// Re-export hook types
export type {
  HookOperation,
  BaseHookContext,
  CreateHookContext,
  ReadHookContext,
  UpdateHookContext,
  DeleteHookContext,
  HookHandler,
  CollectionHooks,
  InferFieldType,
  InferFieldTypes,
}

/**
 * Configuration for auto-generated fields (id, createdAt, updatedAt)
 */
export interface AutoGeneratedFieldsConfig {
  /** Enable/disable id field (default: true) */
  id?: boolean
  /** Enable/disable createdAt field (default: true) */
  createdAt?: boolean
  /** Enable/disable updatedAt field (default: true) */
  updatedAt?: boolean
}

// ============================================================================
// Collection Types
// ============================================================================

/**
 * CollectionConfig - Configuration for creating a collection
 * @typeParam TSlug - The literal slug type (inferred from slug parameter)
 * @typeParam TFields - Record of field names to Field instances
 */
export interface CollectionConfig<
  TSlug extends string = string,
  TFields extends Record<string, Field<unknown>> = Record<string, Field<unknown>>,
> {
  /** Unique identifier for this collection (kebab-case recommended) */
  readonly slug: TSlug

  /** Human-readable name (auto-generated from slug if not provided) */
  readonly name?: string

  /** Admin UI configuration */
  readonly admin?: {
    /** Description shown in admin interface */
    readonly description?: string
    /** Icon name for admin UI */
    readonly icon?: string
  }

  /** Field definitions */
  readonly fields: TFields

  /** Auto-generated fields configuration (default: all enabled) */
  readonly autoGeneratedFields?: AutoGeneratedFieldsConfig

  /** Lifecycle hooks */
  readonly hooks?: CollectionHooks<TSlug, TFields>

  /** Optional metadata */
  readonly meta?: Record<string, unknown>
}

/**
 * Auto-generated field identifiers
 */
export const AUTO_GENERATED_FIELDS = ['id', 'createdAt', 'updatedAt'] as const

/**
 * AutoGeneratedFieldName - Names of automatically generated fields
 */
export type AutoGeneratedFieldName = typeof AUTO_GENERATED_FIELDS[number]

/**
 * CollectionFields - Combined fields including optional auto-generated ones
 * Uses optional fields to accurately reflect runtime behavior
 * @typeParam TFields - User-defined fields
 */
export type CollectionFields<TFields extends Record<string, Field<unknown>>> = TFields & {
  id?: Field<number>
  createdAt?: Field<Date>
  updatedAt?: Field<Date>
}

/**
 * GetCollectionType - Extract TypeScript type from a collection
 * @typeParam T - The collection type
 */
export type GetCollectionType<T> = T extends Collection<infer TFields>
  ? {
      [K in keyof TFields]: TFields[K] extends Field<infer T>
        ? TFields[K]['required'] extends true
          ? T
          : T | undefined
        : never
    }
  : never

/**
 * Collection - A defined collection ready for use
 * @typeParam TSlug - The literal slug type
 * @typeParam TFields - Record of field names to Field instances
 */
export interface Collection<
  TSlug extends string = string,
  TFields extends Record<string, Field<unknown>> = Record<string, Field<unknown>>,
> {
  /** Unique identifier */
  readonly slug: TSlug

  /** Human-readable name */
  readonly name: string

  /** Admin UI configuration */
  readonly admin: {
    readonly description?: string
    readonly icon?: string
  } | null

  /** All fields including auto-generated ones (optional based on config) */
  readonly fields: CollectionFields<TFields>

  /** User-defined fields only (excluding auto-generated) */
  readonly ownFields: TFields

  /** Auto-generated field configuration */
  readonly autoGeneratedFields: AutoGeneratedFieldsConfig

  /** Lifecycle hooks */
  readonly hooks: CollectionHooks<TSlug, TFields>

  /** Metadata */
  readonly meta: Record<string, unknown>

  /** Symbol to prevent accidental property access */
  readonly [Symbol.toStringTag]: 'Collection'
}
