// Collection types - DSL for defining collections

import type { Field } from '../fields'

/**
 * Configuration for auto-generated fields (id, createdAt, updatedAt)
 */
export interface AutoGeneratedFieldsConfig {
  /** Enable/disable id field (default: true) */
  id?: boolean
  /** Enable/disable createdAt field (default: true) */
  createdAt?: boolean
  /** Enable/disable updatedAt field (default: true) */
  updatedAt?: boolean
}

// ============================================================================
// Hook Types
// ============================================================================

/**
 * Operation types for hooks
 */
export type HookOperation = 'create' | 'read' | 'update' | 'delete'

/**
 * Base context for all hooks
 */
export interface BaseHookContext {
  /** Collection slug */
  readonly collection: string
  /** Operation type */
  readonly operation: HookOperation
}

/**
 * Context for create operations
 */
export interface CreateHookContext extends BaseHookContext {
  readonly operation: 'create'
  /** Data being created (can be mutated) */
  data: Record<string, unknown>
}

/**
 * Context for read operations
 */
export interface ReadHookContext extends BaseHookContext {
  readonly operation: 'read'
  /** Query parameters (can be mutated) */
  query: Record<string, unknown>
}

/**
 * Context for update operations
 */
export interface UpdateHookContext extends BaseHookContext {
  readonly operation: 'update'
  /** Update data (can be mutated) */
  data: Record<string, unknown>
  /** Where clause */
  where: Record<string, unknown>
  /** Current record data before update */
  previousData: Record<string, unknown>
}

/**
 * Context for delete operations
 */
export interface DeleteHookContext extends BaseHookContext {
  readonly operation: 'delete'
  /** Where clause */
  where: Record<string, unknown>
  /** Current record data before delete */
  previousData: Record<string, unknown>
}

/**
 * Hook handler function type
 * @typeParam T - The hook context type
 */
export type HookHandler<T extends BaseHookContext> = (
  context: T
) => Promise<T> | T

/**
 * Collection hooks configuration
 * All hooks are optional and run within the same transaction as the operation
 */
export interface CollectionHooks {
  /** Called before any operation (after global beforeOperation) */
  readonly beforeOperation?: HookHandler<BaseHookContext>

  /** Called after any operation (before global afterOperation) */
  readonly afterOperation?: HookHandler<BaseHookContext>

  /** Called before creating a record */
  readonly beforeCreate?: HookHandler<CreateHookContext>

  /** Called after creating a record */
  readonly afterCreate?: HookHandler<CreateHookContext>

  /** Called before updating records */
  readonly beforeUpdate?: HookHandler<UpdateHookContext>

  /** Called after updating records */
  readonly afterUpdate?: HookHandler<UpdateHookContext>

  /** Called before deleting records */
  readonly beforeDelete?: HookHandler<DeleteHookContext>

  /** Called after deleting records */
  readonly afterDelete?: HookHandler<DeleteHookContext>

  /** Called before reading records */
  readonly beforeRead?: HookHandler<ReadHookContext>

  /** Called after reading records */
  readonly afterRead?: HookHandler<ReadHookContext>
}

// ============================================================================
// Collection Types
// ============================================================================

/**
 * CollectionConfig - Configuration for creating a collection
 * @typeParam TFields - Record of field names to Field instances
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface CollectionConfig<TFields extends Record<string, Field<unknown>>> {
  /** Unique identifier for this collection (kebab-case recommended) */
  readonly slug: string

  /** Human-readable name (auto-generated from slug if not provided) */
  readonly name?: string

  /** Admin UI configuration */
  readonly admin?: {
    /** Description shown in admin interface */
    readonly description?: string
    /** Icon name for admin UI */
    readonly icon?: string
  }

  /** Field definitions */
  readonly fields: TFields

  /** Auto-generated fields configuration (default: all enabled) */
  readonly autoGeneratedFields?: AutoGeneratedFieldsConfig

  /** Lifecycle hooks */
  readonly hooks?: CollectionHooks

  /** Optional metadata */
  readonly meta?: Record<string, unknown>
}

/**
 * Auto-generated field identifiers
 */
export const AUTO_GENERATED_FIELDS = ['id', 'createdAt', 'updatedAt'] as const

/**
 * AutoGeneratedFieldName - Names of automatically generated fields
 */
export type AutoGeneratedFieldName = typeof AUTO_GENERATED_FIELDS[number]

/**
 * CollectionFields - Combined fields including optional auto-generated ones
 * Uses optional fields to accurately reflect runtime behavior
 * @typeParam TFields - User-defined fields
 */
export type CollectionFields<TFields extends Record<string, Field<unknown>>> = TFields & {
  id?: Field<string>
  createdAt?: Field<Date>
  updatedAt?: Field<Date>
}

/**
 * GetCollectionType - Extract TypeScript type from a collection
 * @typeParam T - The collection type
 */
export type GetCollectionType<T> = T extends Collection<infer TFields>
  ? {
      [K in keyof TFields]: TFields[K] extends Field<infer T>
        ? TFields[K]['required'] extends true
          ? T
          : T | undefined
        : never
    }
  : never

/**
 * Collection - A defined collection ready for use
 * @typeParam TFields - Record of field names to Field instances
 */
export interface Collection<TFields extends Record<string, Field<unknown>>> {
  /** Unique identifier */
  readonly slug: string

  /** Human-readable name */
  readonly name: string

  /** Admin UI configuration */
  readonly admin: {
    readonly description?: string
    readonly icon?: string
  } | null

  /** All fields including auto-generated ones (optional based on config) */
  readonly fields: CollectionFields<TFields>

  /** User-defined fields only (excluding auto-generated) */
  readonly ownFields: TFields

  /** Auto-generated field configuration */
  readonly autoGeneratedFields: AutoGeneratedFieldsConfig

  /** Lifecycle hooks */
  readonly hooks: CollectionHooks

  /** Metadata */
  readonly meta: Record<string, unknown>

  /** Symbol to prevent accidental property access */
  readonly [Symbol.toStringTag]: 'Collection'
}
